[package]
name = "batpu2"
version = "0.1.0"
edition = "2021"

[features]
default = ["embedded_io"]
embedded_io = ["dep:rand"]

[dependencies]
rand = { version = "0.8.5", features = ["small_rng"], optional = true }
