[package]
name = "batpu2"
version = "0.1.0"
edition = "2021"

[features]
default = ["embedded_io"]
embedded_io = ["dep:rand"]

[dependencies]
arrayvec = "0.7.6"
num_enum = "0.7.3"
rand = { version = "0.8.5", features = ["small_rng"], optional = true }
thiserror = "2.0.4"
